version: '3.1'

services:
  database:
    restart: always
    image: postgres:14.6
    environment:
      POSTGRES_DB: garcon
      POSTGRES_USER: garcon
      POSTGRES_PASSWORD: garcon
    ports:
    - 5432:5432
