logging:
  pattern:
    console: '${CONSOLE_LOG_PATTERN:%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID: }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-30.30logger{0}){cyan} %clr({%mdc}){faint} %m%n%wEx}'

spring:
  application:
    name: garcon
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_EMPTY
    serialization:
      WRITE_ENUMS_USING_TO_STRING: true
    deserialization:
      READ_ENUMS_USING_TO_STRING: true
  task:
    scheduling:
      pool:
        size: 3
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/garcon}
    username: ${JDBC_DATABASE_USERNAME:garcon}
    password: ${JDBC_DATABASE_PASSWORD:garcon}
    maximum-pool-size: 2

server:
  port: ${PORT:8080}
  forward-headers-strategy: native
  tomcat:
    threads:
      min-spare: 2
      max: 10

management:
  server:
    port: ${ACTUATOR_PORT:8081}
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /internal
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

lunch:
  sync:
    interval: ${LUNCH_SYNC_INTERVAL:PT5M}
  repost:
    retry:
      interval: ${LUNCH_REPOST_RETRY_INTERVAL:PT10M}
